### INSCRIPTION
POST http://localhost:5000/api/utilisateurs/inscription
Content-Type: application/json

{
  "prenom": "Anis",
  "nom": "Makhezer",
  "email": "popo@example.com",
  "motDePasse": "anis1234",
  "parcours": "M1 EEA MTI"
}

### CONNEXION
POST http://localhost:5000/api/utilisateurs/connexion
Content-Type: application/json

{
  "email": "anis@example.com",
  "motDePasse": "anis1234"
}

### ➕ AJOUTER UNE NOTE
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmZmNDVmZDFiYWZmMjA2ODU1OTY3YiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ4Mjc5NjIsImV4cCI6MTc0NDgzNTE2Mn0.PT41NjH1vLIjLI2mn-jqmTaq8aEaPNSeTcP2TW2DYt0


{
  "code": "871.1",
  "nom": "Traitement du signal 1",
  "note": 14,
  "coefficient": 1
}

### 📥 RÉCUPÉRER MES NOTES
GET http://localhost:5000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmZmNDVmZDFiYWZmMjA2ODU1OTY3YiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ4Mjc5NjIsImV4cCI6MTc0NDgzNTE2Mn0.PT41NjH1vLIjLI2mn-jqmTaq8aEaPNSeTcP2TW2DYt0


### ✏️ MODIFIER UNE NOTE
PUT http://localhost:5000/api/notes/67fff6bcc157b0b438d8ff11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmZmNDVmZDFiYWZmMjA2ODU1OTY3YiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ4Mjc5NjIsImV4cCI6MTc0NDgzNTE2Mn0.PT41NjH1vLIjLI2mn-jqmTaq8aEaPNSeTcP2TW2DYt0

{
  "note": 16,
  "coefficient": 1.5
}

### 👤 PROFIL UTILISATEUR
GET http://localhost:5000/api/utilisateurs/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmZmNDVmZDFiYWZmMjA2ODU1OTY3YiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ4Mjc5NjIsImV4cCI6MTc0NDgzNTE2Mn0.PT41NjH1vLIjLI2mn-jqmTaq8aEaPNSeTcP2TW2DYt0

### ❌ SUPPRIMER MON COMPTE
DELETE http://localhost:5000/api/utilisateurs/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmZmNDVmZDFiYWZmMjA2ODU1OTY3YiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ4Mjc5NjIsImV4cCI6MTc0NDgzNTE2Mn0.PT41NjH1vLIjLI2mn-jqmTaq8aEaPNSeTcP2TW2DYt0

